# Generated by Django 3.1.4 on 2020-12-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
    ]
